### ISSUE TITLE
Issue in Type 3 filteration - Consolidation Stocks

### ISSUE THREAD

**Issue by Askhay47** [pranjal-joshi/Screeni-py#130]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Askhay47** [comment]
[+] Select an Index for Screening:
     W > Screen stocks from my own Watchlist
     0 > Screen stocks by the stock names (NSE Stock Code)
     1 > Nifty 50               2 > Nifty Next 50           3 > Nifty 100
     4 > Nifty 200              5 > Nifty 500               6 > Nifty Smallcap 50
     7 > Nifty Smallcap 100     8 > Nifty Smallcap 250      9 > Nifty Midcap 50
    10 > Nifty Midcap 100      11 > Nifty Midcap 150       13 > Newly Listed (IPOs in last 2 Year)
    Enter > All Stocks (default)
[+] Select option:

[+] Select a Critera for Stock Screening:

    0 > Full Screening (Shows Technical Parameters without Any Criteria)
    1 > Screen stocks for Breakout or Consolidation
    2 > Screen for the stocks with recent Breakout & Volume
    3 > Screen for the Consolidating stocks
    4 > Screen for the stocks with Lowest Volume in last 'N'-days (Early Breakout Detection)
    5 > Screen for the stocks with RSI
    6 > Screen for the stocks showing Reversal Signals
    7 > Screen for the stocks making Chart Patterns
    8 > Edit user configuration
    9 > Show user configuration
    10 > Show Last Screened Results
    11 > Help / About Developer
    12 > Exit
[+] Select option: 3
[+] Getting Stock Codes From NSE... => Done! Fetched 1820 stock codes.
[+] Stock shuffling is active.
[+] Screening only for the stocks in Stage-2! Edit User Config to change this.
[+] After-Market Stock Data is not cached..
[+] Downloading cache from Screenipy server for faster processing, Please Wait..
[########################################] 35/35 [100%] in 1:02.8 (0.56/s)

[+] Automatically Using Cached Stock Data due to After-Market hours!
[+] Starting Stock Screening.. Press Ctrl+C to stop!


Traceback (most recent call last):.......] .   0/1820 [0%] in 2s (0.0/s, eta: -)
  File "PyInstaller\loader\pyimod02_importers.py", line 298, in get_code
  File "PyInstaller\loader\pyimod01_archive.py", line 302, in extract
MemoryError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "screenipy.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "classes\Fetcher.py", line 14, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "yfinance\__init__.py", line 23, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
Traceback (most recent call last):
  File "yfinance\ticker.py", line 27, in <module>
  File "screenipy.py", line 9, in <module>
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 298, in get_code
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "pandas\__init__.py", line 50, in <module>
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod01_archive.py", line 302, in extract
  File "classes\Screener.py", line 14, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 298, in get_code
MemoryError
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "pandas\core\api.py", line 29, in <module>
  File "PyInstaller\loader\pyimod01_archive.py", line 302, in extract

The above exception was the direct cause of the following exception:

  File "screenipy.py", line 9, in <module>
  File "scipy\signal\__init__.py", line 292, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
MemoryError
Traceback (most recent call last):
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "pandas\core\arrays\__init__.py", line 11, in <module>

The above exception was the direct cause of the following exception:

  File "screenipy.py", line 7, in <module>
  File "screenipy.py", line 9, in <module>
  File "classes\Screener.py", line 14, in <module>
  File "scipy\signal\windows\__init__.py", line 41, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "pandas\core\arrays\interval.py", line 82, in <module>
  File "screenipy.py", line 7, in <module>
  File "classes\Fetcher.py", line 14, in <module>
  File "scipy\signal\__init__.py", line 292, in <module>
  File "scipy\signal\windows\windows.py", line 7, in <module>
  File "classes\Screener.py", line 14, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 476, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 300, in get_code
  File "classes\Fetcher.py", line 14, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "yfinance\__init__.py", line 23, in <module>
  File "scipy\signal\windows\__init__.py", line 41, in <module>
  File "scipy\linalg\__init__.py", line 213, in <module>
ImportError: Loader FrozenImporter cannot handle module pandas.core.indexes.base
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "scipy\signal\__init__.py", line 292, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
[  File "yfinance\__init__.py", line 23, in <module>
  File "yfinance\ticker.py", line 27, in <module>
  File "scipy\signal\windows\windows.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "scipy\linalg\_sketches.py", line 9, in <module>
2  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
6  File "scipy\signal\windows\__init__.py", line 41, in <module>
  File "yfinance\ticker.py", line 27, in <module>
  File "pandas\__init__.py", line 143, in <module>
  File "scipy\linalg\__init__.py", line 195, in <module>
  File "scipy\sparse\__init__.py", line 230, in <module>
8  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
0  File "pandas\__init__.py", line 50, in <module>
  File "pandas\io\api.py", line 39, in <module>
Traceback (most recent call last):
  File "scipy\signal\windows\windows.py", line 7, in <module>
  File "scipy\linalg\misc.py", line 3, in <module>
  File "scipy\sparse\lil.py", line 17, in <module>
]  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 476, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 298, in get_code
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
ImportError: DLL load failed while importing _csparsetools: The paging file is too small for this operation to complete.
   File "pandas\core\api.py", line 48, in <module>
  File "scipy\linalg\__init__.py", line 213, in <module>
  File "scipy\linalg\blas.py", line 213, in <module>
  File "PyInstaller\loader\pyimod01_archive.py", line 302, in extract
[F  File "PyInstaller\loader\pyimod02_importers.py", line 300, in get_code
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
ImportError: DLL load failed while importing _fblas: The paging file is too small for this operation to complete.
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
1aImportError: Loader FrozenImporter cannot handle module pandas.io.stata
MemoryError
  File "pandas\core\groupby\__init__.py", line 1, in <module>
[9i[  File "scipy\linalg\_sketches.py", line 9, in <module>

The above exception was the direct cause of the following exception:

  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
10l8Traceback (most recent call last):
  File "pandas\core\groupby\generic.py", line 76, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
88e5  File "screenipy.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 476, in exec_module
98d2  File "scipy\sparse\__init__.py", line 230, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 300, in get_code
6] 0  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
ImportError: Loader FrozenImporter cannot handle module pandas.core.groupby.groupby
8 t]  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
[  File "classes\Fetcher.py", line 14, in <module>
]Fo 1  File "scipy\sparse\lil.py", line 17, in <module>
 a F4FiTraceback (most recent call last):
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
exTraceback (most recent call last):
0al  File "PyInstaller\loader\pyimod02_importers.py", line 298, in get_code
ImportError: DLL load failed while importing _csparsetools: The paging file is too small for this operation to complete.
ae  File "PyInstaller\loader\pyimod02_importers.py", line 298, in get_code
7ie  File "yfinance\__init__.py", line 23, in <module>
[il  File "PyInstaller\loader\pyimod01_archive.py", line 291, in extract
6ld18e  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
]e c7  File "PyInstaller\loader\pyimod01_archive.py", line 302, in extract
  File "PyInstaller\loader\pyimod01_archive.py", line 87, in __enter__
 d utd  File "yfinance\ticker.py", line 27, in <module>
Ftt4e MemoryError
aio0MemoryError
 t
The above exception was the direct cause of the following exception:

ol  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
 ]
The above exception was the direct cause of the following exception:

soTraceback (most recent call last):
 ee Traceback (most recent call last):
c   File "pandas\__init__.py", line 143, in <module>
  File "screenipy.py", line 9, in <module>
edxe  File "screenipy.py", line 7, in <module>
rex Fc  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
ipetau  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
xtcoit  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "pandas\io\api.py", line 17, in <module>
e  File "classes\Screener.py", line 13, in <module>
u le  File "classes\Fetcher.py", line 14, in <module>0 [0%] in 2s (0.0/s, eta: -)
c  File "PyInstaller\loader\pyimod02_importers.py", line 476, in exec_module
'tee   File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
usexds  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
tc   File "PyInstaller\loader\pyimod02_importers.py", line 300, in get_code
e te s  File "classes\Utility.py", line 16, in <module>
ccorsc  File "yfinance\__init__.py", line 23, in <module>
utImportError: Loader FrozenImporter cannot handle module pandas.io.orc
 ecrrip  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
eerie[t  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
xnip 8 eipts0  File "alive_progress\__init__.py", line 12, in <module>
'cpt c2  File "yfinance\ticker.py", line 27, in <module>
suy 'r8ct''si]re   File "PyInstaller\loader\pyimod02_importers.py", line 476, in exec_module
scr eed  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
creennupeF ipy  File "PyInstaller\loader\pyimod02_importers.py", line 300, in get_code
t 'sie'  File "pandas\__init__.py", line 143, in <module>
eascri nicpImportError: Loader FrozenImporter cannot handle module alive_progress.styles.exhibit
 pdilry[  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
tt pee'1ou'yde d es' n7uu c di3entr  File "pandas\io\api.py", line 24, in <module>
top3 ho u y6taeune']oneehxe  dn a c  File "PyInstaller\loader\pyimod02_importers.py", line 476, in exec_module
FulitnduTraceback (most recent call last):
  File "PyInstaller\loader\pyimod02_importers.py", line 300, in get_code
anepodledImportError: Loader FrozenImporter cannot handle module pandas.io.pickle
ihd exc  File "PyInstaller\loader\pyimod02_importers.py", line 298, in get_code
 [lay ute  File "PyInstaller\loader\pyimod01_archive.py", line 302, in extract
e1en'ueepMemoryError: Out of memory while decompressing data
x4dd nTraceback (most recent call last):
  t
The above exception was the direct cause of the following exception:

c8 ldh  File "PyInstaller\loader\pyimod02_importers.py", line 298, in get_code
tsiTraceback (most recent call last):
e4teua  File "PyInstaller\loader\pyimod01_archive.py", line 302, in extract
oco  File "screenipy.py", line 7, in <module>
p0odenMemoryError
 rn  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
t]   d
The above exception was the direct cause of the following exception:

ui!  File "classes\Fetcher.py", line 16, in <module>
i eetlTraceback (most recent call last):
np
  File "PyInstaller\loader\pyimod02_importers.py", line 476, in exec_module
onFxoe  File "screenipy.py", line 9, in <module>
ht  File "PyInstaller\loader\pyimod02_importers.py", line 300, in get_code
x!ac d  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
a ImportError: Loader FrozenImporter cannot handle module nsetools
e
ieu   File "classes\Screener.py", line 14, in <module>
n'[clpne  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
ds4uethx  File "scipy\signal\__init__.py", line 292, in <module>
lc6tdiac  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
er3e one  File "scipy\signal\windows\__init__.py", line 41, in <module>
de2 tndp  File "PyInstaller\loader\pyimod02_importers.py", line 476, in exec_module
 enso!lt  File "PyInstaller\loader\pyimod02_importers.py", line 300, in get_code
e]ic
eiImportError: Loader FrozenImporter cannot handle module scipy.signal.windows.windows
xcpredo[ eFix n1pyaptex2tie 'c'2ilcuse 1oedtcpd2n! trtu]!
eoeion!
 ee
 en Fscitoxrpa uiyienp' chtldua euen'd  dledtott s e scroexceptuipt 'screenipy' due tocrn  unhandled excepeiehtxecutoenipnaion!ndled exception!
ey!
 'MemoryError

sMemoryError
 MemoryError

**Comment by Askhay47** [comment]
I downloaded V1.37 after error in V1.38
I use windows 11, V21H2
I have acer preditos helios 300
Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.21 GHz
8 gb ram

**Comment by Askhay47** [comment]
Hey You there ?

**Comment by pranjal-joshi** [comment]
Traveling for a vacation.
Will try to fix this soon 👍🏼
@Askhay47

**Comment by pranjal-joshi** [comment]
Hi @Askhay47 

Please try downloading this newly built EXE: https://github.com/pranjal-joshi/Screeni-py/releases/download/1.38/screenipy.exe
