### ISSUE TITLE
After market data access

### ISSUE THREAD

**Issue by maurya19** [pranjal-joshi/Screeni-py#175]
**Describe the bug**
I have clean install of screeipy. After market hours i try to do analysis then i am getting error.
hence tried to download data  then error is as follows

**To Reproduce**
1. run python src/screenipy.py -d
2. After some time  below is output

[+] Download ONLY mode! Stocks will not be screened!
[+] Getting Stock Codes From NSE... => Done! Fetched 1904 stock codes.
[+] Stock shuffling is active.
[+] Screening only for the stocks in Stage-2! Edit User Config to change this.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\ProgramData\Anaconda3\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\ProgramData\Anaconda3\lib\ssl.py", line 1041, in _create
    self.do_handshake()
  File "C:\ProgramData\Anaconda3\lib\ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.github.com', port=443): Max retries exceeded with url: /pranjal-joshi/Screeni-py/actions-data-download/actions-data-download/stock_data_020523.pkl (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1943720/235736551-df7df47d-3e21-48e3-ba3b-e89d55dbdeec.png)

**Desktop (please complete the following information):**
 - OS: windows 11

**Additional context**
i feel  i am not able to access 
url: /pranjal-joshi/Screeni-py/actions-data-download/actions-data-download/stock_data_020523.pkl

and i dont see  folder https://github.com/pranjal-joshi/Screeni-py/actions-data-download/

**Comment by pranjal-joshi** [comment]
The issue seems to be with a secure network connection - I haven't implemented any GitHub auth but it seems like it worked only after you logged in for your device.
Issue-related discussion - https://t.me/c/1859052749/324
Closing as of now as it is self resolved
