### ISSUE TITLE
cuda drivers error

### ISSUE THREAD

**Issue by vineetb03** [pranjal-joshi/Screeni-py#232]
Hi,

Windows 11 machine, 16 GB RAM

While starting the app, I am getting below error:

2024-01-20 23:43:17 
2024-01-20 23:43:17 Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.
2024-01-20 23:43:17 
2024-01-20 23:43:17 
2024-01-20 23:43:17   You can now view your Streamlit app in your browser.
2024-01-20 23:43:17 
2024-01-20 23:43:17   URL: http://0.0.0.0:8501
2024-01-20 23:43:17 
2024-01-20 23:43:18 2024-01-21 04:43:18.825680: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-20 23:43:18 2024-01-21 04:43:18.864507: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-20 23:43:18 2024-01-21 04:43:18.864569: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-20 23:43:18 2024-01-21 04:43:18.865645: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-20 23:43:18 2024-01-21 04:43:18.871724: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-20 23:43:18 2024-01-21 04:43:18.872093: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
2024-01-20 23:43:18 To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-20 23:43:19 2024-01-21 04:43:19.869722: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

Also if I ignore the error then while searching for any result, getting below error:

2024-01-20 23:45:36 [+] Getting Stock Codes From NSE... list index out of range
2024-01-20 23:45:36 Exception in thread Thread-11 (dummy_call):
2024-01-20 23:45:36 Traceback (most recent call last):
2024-01-20 23:45:36   File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
2024-01-20 23:45:36     self.run()
2024-01-20 23:45:36   File "/usr/local/lib/python3.11/threading.py", line 982, in run
2024-01-20 23:45:36     self._target(*self._args, **self._kwargs)
2024-01-20 23:45:36   File "/opt/program/src/streamlit_app.py", line 116, in dummy_call
2024-01-20 23:45:36     screenipy_main(execute_inputs=execute_inputs, isDevVersion=isDevVersion, backtestDate=backtestDate)
2024-01-20 23:45:36   File "/opt/program/src/screenipy.py", line 370, in main
2024-01-20 23:45:36     listStockCodes = fetcher.fetchStockCodes(tickerOption, proxyServer=proxyServer)
2024-01-20 23:45:36                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-20 23:45:36   File "/opt/program/src/classes/Fetcher.py", line 202, in fetchStockCodes
2024-01-20 23:45:36     input(
2024-01-20 23:45:36 EOFError: EOF when reading a line

Pls help. Thanks.

**Comment by pranjal-joshi** [comment]
Cuda drivers not exists is a warning and not an error. It says GPU is not available for accelerated screening.

The EOF error you're receiving is most like corrupted cache file or network issue

Try clearing cached stock data and try again

**Comment by vineetb03** [comment]
Can you please let me know the steps to delete the clearing cached stock data in docker setup. Also I don't think its a network issue as I am able to access on web.

**Comment by pranjal-joshi** [comment]
Clear cache data button is given in the UI on homepage

**Comment by vineetb03** [comment]
Tried clearing the cache under development options. Please check the attached screenshot but no luck getting same " EOFError: EOF when reading a line" as pasted above.

![clear_cache](https://github.com/pranjal-joshi/Screeni-py/assets/157265743/a0c4aee6-caec-4992-9fd1-0bbc113eb8b9)

**Comment by pranjal-joshi** [comment]
This is not the cache I'm referring to.

You will see a clear cache button after screening stocks along with the results table.

If you're not on the latest version of Screenipy docker, upgrade it

**Comment by vineetb03** [comment]
Actually in my case screening is not happening…the app stuck on screening
after button click. And after that have to stop the app.

While logs I can see the error. I did the setup yesterday itself, hoping
will be on latest one.

Pls suggest.

**Comment by vineetb03** [comment]
I just checked the nseindia site is down, may be it’s a issue related to
that.
